name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      
jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install HTMLHint
      run: npm install -g htmlhint

    - name: Lint HTML
      run: htmlhint index.html

    - name: Install stylelint
      run: |
        npm install -g stylelint stylelint-config-standard
        echo '{
        "extends": "stylelint-config-standard"
        }' > .stylelintrc.json

    - name: Lint CSS
      run: stylelint styles.css 

    - name: Install hadolint
      run: |
        sudo wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/latest/download/hadolint-Linux-x86_64
        sudo chmod +x /bin/hadolint

    - name: Lint Dockerfile
      run: hadolint Dockerfile

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: kkmm552/lab4:latest

  terraform:
    name: Terraform Init/Plan/Apply
    runs-on: ubuntu-latest
    needs: build-deploy

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}  # якщо потрібна

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Init
      run: terraform init

    - name: Terraform Format Check
      run: terraform fmt -check

    - name: Terraform Plan
      run: terraform plan -out=tfplan

    - name: Terraform Apply
      if: github.ref == 'refs/heads/main'
      run: terraform apply -auto-approve tfplan
